# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160511_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='random_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
