# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20160511_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='random_number',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
